//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.27 at 01:21:42 PM BST 
//


package org.jcp.xml.ns.sipservlet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The identity-assertionType is used to configure the identity-assertion
 *         scheme that should be used and whether the scheme is required or
 *         supported.
 * 
 *         Used in: login-config
 *       
 * 
 * <p>Java class for identity-assertionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identity-assertionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identity-assertion-scheme" type="{http://www.jcp.org/xml/ns/sipservlet}identity-assertion-schemeType"/>
 *         &lt;element name="identity-assertion-support" type="{http://www.jcp.org/xml/ns/sipservlet}identity-assertion-supportType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identity-assertionType", propOrder = {
    "identityAssertionScheme",
    "identityAssertionSupport"
})
public class IdentityAssertionType {

    @XmlElement(name = "identity-assertion-scheme", required = true)
    protected IdentityAssertionSchemeType identityAssertionScheme;
    @XmlElement(name = "identity-assertion-support")
    protected IdentityAssertionSupportType identityAssertionSupport;

    /**
     * Gets the value of the identityAssertionScheme property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityAssertionSchemeType }
     *     
     */
    public IdentityAssertionSchemeType getIdentityAssertionScheme() {
        return identityAssertionScheme;
    }

    /**
     * Sets the value of the identityAssertionScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityAssertionSchemeType }
     *     
     */
    public void setIdentityAssertionScheme(IdentityAssertionSchemeType value) {
        this.identityAssertionScheme = value;
    }

    /**
     * Gets the value of the identityAssertionSupport property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityAssertionSupportType }
     *     
     */
    public IdentityAssertionSupportType getIdentityAssertionSupport() {
        return identityAssertionSupport;
    }

    /**
     * Sets the value of the identityAssertionSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityAssertionSupportType }
     *     
     */
    public void setIdentityAssertionSupport(IdentityAssertionSupportType value) {
        this.identityAssertionSupport = value;
    }

}
