//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.27 at 01:21:42 PM BST 
//


package org.jcp.xml.ns.sipservlet;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.sun.java.xml.ns.javaee.DescriptionType;
import com.sun.java.xml.ns.javaee.DisplayNameType;
import com.sun.java.xml.ns.javaee.EjbLocalRefType;
import com.sun.java.xml.ns.javaee.EjbRefType;
import com.sun.java.xml.ns.javaee.EmptyType;
import com.sun.java.xml.ns.javaee.EnvEntryType;
import com.sun.java.xml.ns.javaee.IconType;
import com.sun.java.xml.ns.javaee.LifecycleCallbackType;
import com.sun.java.xml.ns.javaee.ListenerType;
import com.sun.java.xml.ns.javaee.LocaleEncodingMappingListType;
import com.sun.java.xml.ns.javaee.MessageDestinationRefType;
import com.sun.java.xml.ns.javaee.MessageDestinationType;
import com.sun.java.xml.ns.javaee.NonEmptyStringType;
import com.sun.java.xml.ns.javaee.ParamValueType;
import com.sun.java.xml.ns.javaee.PersistenceContextRefType;
import com.sun.java.xml.ns.javaee.PersistenceUnitRefType;
import com.sun.java.xml.ns.javaee.ResourceEnvRefType;
import com.sun.java.xml.ns.javaee.ResourceRefType;
import com.sun.java.xml.ns.javaee.SecurityRoleType;
import com.sun.java.xml.ns.javaee.ServiceRefType;
import com.sun.java.xml.ns.javaee.ServletType;
import com.sun.java.xml.ns.javaee.SessionConfigType;


/**
 * 
 *         The sip-app element is the root of the deployment descriptor for
 *         a SIP servlet application. Note that the sub-elements of this element can be
 *         in the arbitrary order. Because of that, the multiplicity of the elements of distributable,
 *         session-config, proxy-config, and login-config was changed from "?" to "*" in this schema.
 *         However, the deployment descriptor instance file must not contain multiple elements of distributable,
 *         session-config, proxy-config, and login-config.
 *       
 * 
 * <p>Java class for sip-appType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sip-appType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="app-name" type="{http://java.sun.com/xml/ns/javaee}nonEmptyStringType"/>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="distributable" type="{http://java.sun.com/xml/ns/javaee}emptyType"/>
 *         &lt;element name="context-param" type="{http://java.sun.com/xml/ns/javaee}param-valueType"/>
 *         &lt;element name="listener" type="{http://java.sun.com/xml/ns/javaee}listenerType"/>
 *         &lt;element name="servlet-selection" type="{http://www.jcp.org/xml/ns/sipservlet}servlet-selectionType"/>
 *         &lt;element name="servlet" type="{http://java.sun.com/xml/ns/javaee}servletType"/>
 *         &lt;element name="proxy-config" type="{http://www.jcp.org/xml/ns/sipservlet}proxy-configType"/>
 *         &lt;element name="session-config" type="{http://java.sun.com/xml/ns/javaee}session-configType"/>
 *         &lt;element name="security-constraint" type="{http://www.jcp.org/xml/ns/sipservlet}security-constraintType"/>
 *         &lt;element name="login-config" type="{http://www.jcp.org/xml/ns/sipservlet}login-configType"/>
 *         &lt;element name="security-role" type="{http://java.sun.com/xml/ns/javaee}security-roleType"/>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}jndiEnvironmentRefsGroup"/>
 *         &lt;element name="message-destination" type="{http://java.sun.com/xml/ns/javaee}message-destinationType"/>
 *         &lt;element name="locale-encoding-mapping-list" type="{http://java.sun.com/xml/ns/javaee}locale-encoding-mapping-listType"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{http://www.jcp.org/xml/ns/sipservlet}sip-app-versionType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sip-appType", propOrder = {
    "appNameOrDescriptionAndDisplayName"
})
public class SipAppType {

    @XmlElementRefs({
        @XmlElementRef(name = "icon", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "servlet", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "app-name", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "security-constraint", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "context-param", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "session-config", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "security-role", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "login-config", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pre-destroy", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ejb-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "message-destination-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resource-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "servlet-selection", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "message-destination", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resource-env-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ejb-local-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "locale-encoding-mapping-list", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "persistence-context-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "env-entry", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "proxy-config", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "service-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "persistence-unit-ref", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "post-construct", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "distributable", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "display-name", namespace = "http://java.sun.com/xml/ns/javaee", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "listener", namespace = "http://www.jcp.org/xml/ns/sipservlet", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> appNameOrDescriptionAndDisplayName;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the appNameOrDescriptionAndDisplayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appNameOrDescriptionAndDisplayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppNameOrDescriptionAndDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IconType }{@code >}
     * {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServletType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonEmptyStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link SecurityConstraintType }{@code >}
     * {@link JAXBElement }{@code <}{@link ParamValueType }{@code >}
     * {@link JAXBElement }{@code <}{@link SessionConfigType }{@code >}
     * {@link JAXBElement }{@code <}{@link SecurityRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link LoginConfigType }{@code >}
     * {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}
     * {@link JAXBElement }{@code <}{@link EjbRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link MessageDestinationRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResourceRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServletSelectionType }{@code >}
     * {@link JAXBElement }{@code <}{@link MessageDestinationType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResourceEnvRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link EjbLocalRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link LocaleEncodingMappingListType }{@code >}
     * {@link JAXBElement }{@code <}{@link PersistenceContextRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link EnvEntryType }{@code >}
     * {@link JAXBElement }{@code <}{@link ProxyConfigType }{@code >}
     * {@link JAXBElement }{@code <}{@link ServiceRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link PersistenceUnitRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link LifecycleCallbackType }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyType }{@code >}
     * {@link JAXBElement }{@code <}{@link DisplayNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link ListenerType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getAppNameOrDescriptionAndDisplayName() {
        if (appNameOrDescriptionAndDisplayName == null) {
            appNameOrDescriptionAndDisplayName = new ArrayList<JAXBElement<?>>();
        }
        return this.appNameOrDescriptionAndDisplayName;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
